--Database queries:
--1.create database test;
--2.drop database test;
--3.backup database test to disk='C:\test.bak';
--4.backup database test to disk='D:\test.bak' with differential; (backup latest changes only)
--5.use test;

--Table queries:
--1.create table persons(PersonID int, LastName varchar(255), FirstName varchar(255), Address varchar(255), City varchar(255));
--2.create table specific_person_details as select PersonID,FirstName from persons
--3.drop table persons;
--4.truncate table persons;

--Table column queries:
--1.alter table persons add phone varchar(255);
--2.alter table persons drop column phone;
--3.alter table persons rename column city to country;

--Table column datatype queries:
--1.alter table persons alter column address type text;

--Constraints
--1.create table persons(PersonID int not null, LastName varchar(255) not null, FirstName varchar(255) not null, Address varchar(255), City varchar(255));
--2.alter table persons alter column address set not null;
--3.create table data(DataID int not null unique);
--4.create table datas(DataID int not null, DataDetails varchar(255) not null, constraint UC_Data unique(DataID,DataDetails));
--5.alter table persons add unique(PersonID);
--6.alter table datas add constraint uc_multiple unique(DataID,DataDetails);
--7.alter table datas drop constraint uc_multiple;
--8.create table record(id int not null primary key);
--9.create table demos(ID int not null, Code varchar(255), name varchar(255), constraint PK_Demo primary key(ID,Code));
--10.create table testdemo(ID int not null);
--11.alter table testdemo add primary key (ID);
--12.alter table testdemo add name varchar(255) not null;
--13.alter table testdemo drop constraint testdemo_pkey;
--13.alter table testdemo add constraint pk_testdemo primary key(ID,name);
--14.alter table persons add primary key(PersonID);
--15.create table orders(OrderID int not null, OrderDetails varchar(255), primary key(OrderID), PersonID int, foreign key(PersonID) references persons(PersonID));
--16.create table tasks(ID int not null primary key, TaskName varchar(255), PersonID int, Constraint FK_PersonTask foreign key(PersonID) references persons(PersonID));
--17.alter table tasks drop constraint FK_PersonTask;
--18.alter table tasks add constraint FK_PersonTask foreign key(PersonID) references persons(PersonID);
--19.create table citydata(ID int not null primary key, CandidatesName varchar(255), Age int, City varchar(255), constraint chk_citydata check((Age >= 18) and City ='Salem'));
--20.alter table citydata add constraint chk_citydatacandidate check(CandidatesName = 'Ezhil');
--21.alter table citydata drop constraint chk_citydatacandidate;
